apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}
spec:
  ports:
    - port: 3000
      protocol: TCP
      targetPort: http-grafana
  selector:
    app: {{ .Values.app.name }}
  sessionAffinity: None
  type: {{ .Values.service.type }}

